name: clear-memory-cache # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple clear memory cache app # 79 char long summary
description: |
  Had memory cache overflowing?
  Closed a previuse app and the memory is still too high?
  Just click the button and you are done.

grade: devel # must be 'stable' to release into candidate/stable channels
base: core18
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  clear-memory-cache:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - python-six
